[project]
name = "flet-app"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Bernardo", email = "you@example.com" }
]
dependencies = [
    "flet[all]>=0.80.5",
    "numpy>=2.2.6",
    "pandas>=2.3.3",
    "python-calamine>=0.6.2",
    "xlsxwriter>=3.2.9",
]

[dependency-groups]
dev = [
    "flet-cli>=0.80.5",
    "flet-desktop>=0.80.5",
    "flet-web>=0.80.5",
]

[tool.flet]
org = "com.mycompany"
product = "flet-app"
company = "Flet"
copyright = "Copyright (C) 2023-2026 by Flet"

[tool.flet.app]
path = "src"
